import { useEffect, useRef, useState } from 'react';
import { actor, identity, apiErrorToMessage, CANISTER_ID } from './ic.js';

export default function App() {
  const [language, setLanguage] = useState('English');
  const [topic, setTopic] = useState('');
  const [phase, setPhase] = useState('idle'); // idle | loading | done | error
  const [quote, setQuote] = useState('');
  const [errorMsg, setErrorMsg] = useState('');
  const [paused, setPaused] = useState(false);
  const [elapsed, setElapsed] = useState(0);
  const timerRef = useRef(null);

  useEffect(() => {
    actor
      .getPauseIconfuciusFlag()
      .then((res) => {
        if ('Ok' in res && res.Ok.flag) setPaused(true);
      })
      .catch(() => {
        // Treat a failed query as not-paused; the update call reports pause too.
      });
    return () => clearInterval(timerRef.current);
  }, []);

  const canGenerate = phase !== 'loading' && !paused && topic.trim() !== '';

  async function generate(e) {
    e.preventDefault();
    if (!canGenerate) return;
    setPhase('loading');
    setQuote('');
    setErrorMsg('');
    setElapsed(0);
    const startTime = Date.now();
    timerRef.current = setInterval(() => {
      setElapsed(Math.floor((Date.now() - startTime) / 1000));
    }, 1000);
    try {
      const res = await actor.IConfuciusSays({ [language]: null }, topic.trim());
      if ('Ok' in res) {
        setQuote(res.Ok);
        setPhase('done');
      } else {
        setErrorMsg(apiErrorToMessage(res.Err));
        setPhase('error');
      }
    } catch (err) {
      setErrorMsg(`Call failed — please try again. (${err.message})`);
      setPhase('error');
    } finally {
      clearInterval(timerRef.current);
    }
  }

  return (
    <div className="app">
      <header>
        <img className="logo" src="/IConfucius.jpg" alt="IConfucius" />
        <h1>IConfucius</h1>
        <p className="tagline">On-chain wisdom, generated by an LLM living on the Internet Computer</p>
      </header>

      {paused && (
        <div className="banner">IConfucius is paused for maintenance. Please come back later.</div>
      )}

      <form onSubmit={generate}>
        <div className="segmented">
          <button
            type="button"
            className={language === 'English' ? 'active' : ''}
            onClick={() => setLanguage('English')}
          >
            English
          </button>
          <button
            type="button"
            className={language === 'Chinese' ? 'active' : ''}
            onClick={() => setLanguage('Chinese')}
          >
            中文
          </button>
        </div>
        <input
          type="text"
          value={topic}
          maxLength={100}
          placeholder={language === 'Chinese' ? '主题，例如：加密货币' : 'A topic, e.g. crypto'}
          onChange={(e) => setTopic(e.target.value)}
          disabled={phase === 'loading' || paused}
        />
        <button type="submit" className="generate" disabled={!canGenerate}>
          {phase === 'loading' ? 'Generating…' : 'IConfucius says…'}
        </button>
      </form>

      {phase === 'loading' && (
        <div className="loading">
          <div className="spinner" />
          <p>
            IConfucius is meditating on your topic… {elapsed}s elapsed
            <br />
            <span className="hint">
              The quote is written token by token by an on-chain LLM — this typically takes 30–90 seconds.
            </span>
          </p>
        </div>
      )}

      {phase === 'done' && (
        <blockquote className="quote">
          <p>{quote}</p>
          <footer>— IConfucius, on {topic.trim()}</footer>
        </blockquote>
      )}

      {phase === 'error' && <div className="error">{errorMsg}</div>}

      <footer className="page-footer">
        Calling canister {CANISTER_ID} as ephemeral principal{' '}
        <code>{identity.getPrincipal().toText()}</code>
      </footer>
    </div>
  );
}
