import { useEffect, useRef, useState } from 'react';
import { actor, apiErrorToMessage } from './ic.js';

const STRINGS = {
  English: {
    htmlLang: 'en',
    tagline: 'On-chain wisdom, generated by an LLM living on the Internet Computer',
    paused: 'IConfucius is paused for maintenance. Please come back later.',
    placeholder: 'A topic, e.g. crypto',
    generate: 'IConfucius says…',
    generating: 'Generating…',
    meditating: (elapsed) => `IConfucius is meditating on your topic… ${elapsed}s elapsed`,
    hint: 'The quote is written token by token by an on-chain LLM — this typically takes 30–90 seconds.',
    attribution: (topic) => `— IConfucius, on ${topic}`,
    callFailed: (msg) => `Call failed — please try again. (${msg})`,
  },
  Chinese: {
    htmlLang: 'zh',
    tagline: '链上智慧，由运行在互联网计算机上的大语言模型生成',
    paused: 'IConfucius 正在维护中，请稍后再来。',
    placeholder: '主题，例如：加密货币',
    generate: '孔子曰…',
    generating: '生成中…',
    meditating: (elapsed) => `IConfucius 正在冥思你的主题… 已用 ${elapsed} 秒`,
    hint: '名言由链上大语言模型逐字生成——通常需要 30 至 90 秒。',
    attribution: (topic) => `——IConfucius，论${topic}`,
    callFailed: (msg) => `调用失败——请重试。（${msg}）`,
  },
  Dutch: {
    htmlLang: 'nl',
    tagline: 'On-chain wijsheid, gegenereerd door een LLM op de Internet Computer',
    paused: 'IConfucius is gepauzeerd voor onderhoud. Kom later terug.',
    placeholder: 'Een onderwerp, bijv. crypto',
    generate: 'IConfucius zegt…',
    generating: 'Genereren…',
    meditating: (elapsed) => `IConfucius mediteert over je onderwerp… ${elapsed}s verstreken`,
    hint: 'Het citaat wordt token voor token geschreven door een on-chain LLM — dit duurt meestal 30–90 seconden.',
    attribution: (topic) => `— IConfucius, over ${topic}`,
    callFailed: (msg) => `Aanroep mislukt — probeer het opnieuw. (${msg})`,
  },
  German: {
    htmlLang: 'de',
    tagline: 'On-Chain-Weisheit, generiert von einem LLM auf dem Internet Computer',
    paused: 'IConfucius ist wegen Wartung pausiert. Bitte später wiederkommen.',
    placeholder: 'Ein Thema, z. B. Krypto',
    generate: 'IConfucius sagt…',
    generating: 'Generiere…',
    meditating: (elapsed) => `IConfucius meditiert über dein Thema… ${elapsed}s vergangen`,
    hint: 'Das Zitat wird Token für Token von einem On-Chain-LLM geschrieben — das dauert in der Regel 30–90 Sekunden.',
    attribution: (topic) => `— IConfucius, über ${topic}`,
    callFailed: (msg) => `Aufruf fehlgeschlagen — bitte erneut versuchen. (${msg})`,
  },
  Hindi: {
    htmlLang: 'hi',
    tagline: 'ऑन-चेन ज्ञान, इंटरनेट कंप्यूटर पर चल रहे LLM द्वारा जनित',
    paused: 'IConfucius रखरखाव के लिए रुका हुआ है। कृपया बाद में आएं।',
    placeholder: 'एक विषय, जैसे क्रिप्टो',
    generate: 'IConfucius कहते हैं…',
    generating: 'बना रहे हैं…',
    meditating: (elapsed) => `IConfucius आपके विषय पर मनन कर रहे हैं… ${elapsed} सेकंड बीते`,
    hint: 'सूक्ति ऑन-चेन LLM द्वारा टोकन-दर-टोकन लिखी जाती है — इसमें आमतौर पर 30–90 सेकंड लगते हैं।',
    attribution: (topic) => `— IConfucius, ${topic} पर`,
    callFailed: (msg) => `कॉल विफल — कृपया पुनः प्रयास करें। (${msg})`,
  },
};

const LANGUAGES = [
  { key: 'English', label: 'English' },
  { key: 'Chinese', label: '中文' },
  { key: 'Dutch', label: 'Nederlands' },
  { key: 'German', label: 'Deutsch' },
  { key: 'Hindi', label: 'हिन्दी' },
];

export default function App() {
  const [language, setLanguage] = useState('English');
  const [topic, setTopic] = useState('');
  const [phase, setPhase] = useState('idle'); // idle | loading | done | error
  const [quote, setQuote] = useState('');
  const [quoteTopic, setQuoteTopic] = useState('');
  const [errorMsg, setErrorMsg] = useState('');
  const [paused, setPaused] = useState(false);
  const [elapsed, setElapsed] = useState(0);
  const timerRef = useRef(null);
  const t = STRINGS[language];

  useEffect(() => {
    actor
      .getPauseIconfuciusFlag()
      .then((res) => {
        if ('Ok' in res && res.Ok.flag) setPaused(true);
      })
      .catch(() => {
        // Treat a failed query as not-paused; the update call reports pause too.
      });
    return () => clearInterval(timerRef.current);
  }, []);

  useEffect(() => {
    document.documentElement.lang = t.htmlLang;
  }, [t]);

  const canGenerate = phase !== 'loading' && !paused && topic.trim() !== '';

  async function generate(e) {
    e.preventDefault();
    if (!canGenerate) return;
    setPhase('loading');
    setQuote('');
    setErrorMsg('');
    setElapsed(0);
    const startTime = Date.now();
    timerRef.current = setInterval(() => {
      setElapsed(Math.floor((Date.now() - startTime) / 1000));
    }, 1000);
    try {
      const res = await actor.IConfuciusSays({ [language]: null }, topic.trim());
      if ('Ok' in res) {
        setQuote(res.Ok);
        setQuoteTopic(topic.trim());
        setPhase('done');
      } else {
        setErrorMsg(apiErrorToMessage(res.Err, language));
        setPhase('error');
      }
    } catch (err) {
      setErrorMsg(t.callFailed(err.message));
      setPhase('error');
    } finally {
      clearInterval(timerRef.current);
    }
  }

  return (
    <div className="app">
      <div className="segmented">
        {LANGUAGES.map(({ key, label }) => (
          <button
            key={key}
            type="button"
            className={language === key ? 'active' : ''}
            onClick={() => setLanguage(key)}
          >
            {label}
          </button>
        ))}
      </div>

      <header>
        <img className="logo" src="/IConfucius.jpg" alt="IConfucius" />
        <h1>IConfucius</h1>
        <p className="tagline">{t.tagline}</p>
      </header>

      {paused && <div className="banner">{t.paused}</div>}

      <form onSubmit={generate}>
        <input
          type="text"
          value={topic}
          maxLength={100}
          placeholder={t.placeholder}
          onChange={(e) => setTopic(e.target.value)}
          disabled={phase === 'loading' || paused}
        />
        <button type="submit" className="generate" disabled={!canGenerate}>
          {phase === 'loading' ? t.generating : t.generate}
        </button>
      </form>

      {phase === 'loading' && (
        <div className="loading">
          <div className="spinner" />
          <p>
            {t.meditating(elapsed)}
            <br />
            <span className="hint">{t.hint}</span>
          </p>
        </div>
      )}

      {phase === 'done' && (
        <blockquote className="quote">
          <p>{quote}</p>
          <footer>{t.attribution(quoteTopic)}</footer>
        </blockquote>
      )}

      {phase === 'error' && <div className="error">{errorMsg}</div>}
    </div>
  );
}
